# Safety vulnerability scanner policy
# This file documents accepted security risks and their justifications

# Security settings
security:
  # Ignore these specific vulnerabilities with justification
  ignore-vulnerabilities:
    # PyTorch CVEs - Low risk for this offline application
    76771:  # CVE-2025-32434 - PyTorch <2.6.0
      reason: >
        This project uses PyTorch only for loading the Silero VAD model.
        The vulnerability relates to GPU tensor operations which are not used
        in this CPU-only offline application. No untrusted input is processed
        by PyTorch operations.
      expires: '2026-06-01'

    78828:  # CVE-2025-2953 - PyTorch <2.7.1-rc1
      reason: >
        DoS vulnerability in MKLDNN operations. This project does not use
        MKLDNN-specific operations. VAD model loading uses standard torch.hub
        which is not affected by this specific vulnerability.
      expires: '2026-06-01'

    76769:  # CVE-2025-3730 - PyTorch <2.8.0
      reason: >
        This is a disputed vulnerability. The project uses PyTorch in a
        controlled, offline environment with no network access or untrusted
        input. Model loading is from a pinned, verified repository.
      expires: '2026-06-01'

  # Continue on vulnerability error (for CI)
  continue-on-vulnerability-error: false

# Note: These vulnerabilities will be re-evaluated when updating dependencies
# Run: make update to check for new PyTorch versions
